version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./kvsmooth:/code
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    networks:
      - internal-network

  redis:
    image: redis 
    networks:
      - internal-network

  celery:
    build:
      context: .  
    command: ['celery', '-A', 'profiles_project', 'worker', '--loglevel=info']
    volumes:
      - ./kvsmooth:/code
    depends_on:
      - app
      - redis
    networks:
      - internal-network

  flower:
    build:
      context: .  
    command: ['celery', '-A', 'profiles_project', 'flower', '--port=5566', 'http://localhost:5566/']
    volumes:
      - ./kvsmooth:/code
    ports:
      - 5555:5555
    depends_on:
      - celery
      - redis
    networks:
      - internal-network
networks:
  internal-network:
    external: false