version: "3"

services:
  redis:
    image: redis 
    ports:
      - "6379:6379"
    networks:
      - internal-network

  app:
    build:
      context: .
    restart: always 
    ports:
      - "8000:8000"
    volumes:
      - ./kvsmooth:/code
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    links:
      - redis
    depends_on:
      - redis
    networks:
      - internal-network


  celery:
    build:
      context: .  
    restart: always
    command: celery -A profiles_project worker --loglevel=info
    volumes:
      - ./kvsmooth:/code
    depends_on:
      - app
      - redis
    networks:
      - internal-network

  flower:
    image: mher/flower:0.9.7  
    command: ['flower', '--broker=redis://redis:6379', '--port=5566']
    volumes:
      - ./kvsmooth:/code
    ports:
      - 5566:5566
    depends_on:
      - app
      - celery
      - redis
    networks:
      - internal-network
networks:
  internal-network:
    external: false